apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: hello
          image: laenfantsterribles/hello-node
          ports:
            - containerPort: 3000
          env:
            - name: ENV_VALUE
              value: "Hello from Kubernetes!"

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
